### ISSUE TITLE
Conflict with Rails 4.2.6 and Mongoid 5.1.1

### ISSUE THREAD

**Issue by tagliala** [heroku/rails_stdout_logging#23]
Hi,

I'm using this gem via `rails_12factor` and there is an issue with the latest Rails 4.2.6 and mongoid (5.1.1, but maybe older)

Here it is a reduced test case
https://github.com/tagliala/mongoid-rails-426/tree/rails_stdout_logging
```
~/dev/tests/mongoid-rails-426 on rails_stdout_logging $ rake routes
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb:23:in `level'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:250:in `set_log_levels'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:132:in `load_configuration'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:88:in `load!'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid.rb:99:in `load!'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/railtie.rb:59:in `block in <class:Railtie>'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
~/dev/tests/mongoid-rails-426/config/environment.rb:5:in `<top (required)>'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => routes => environment
(See full trace by running task with --trace)
```

Rails 4.2.5 was fine
https://github.com/tagliala/mongoid-rails-425/tree/rails_stdout_logging

```bash
~/dev/tests/mongoid-rails-425 on rails_stdout_logging $ rake routes
You don't have any routes defined!

Please add some routes in config/routes.rb.

For more information about routes, see the Rails guide: http://guides.rubyonrails.org/routing.html.
```

Rails 4.2.6 with postgresql is also fine

This issue makes applications impossible to deploy on Heroku because `rake assets:precompile` will fail

Example: https://github.com/diowa/ruby2-rails4-bootstrap-heroku/tree/mongoid

Please try the "Deploy to Heroku" button. You could also try the `master` branch, which does not use mongoid

**Comment by miyucy** [comment]
I'm facing same problem. Could you try with my PR #22 ?

**Comment by tagliala** [comment]
Your PR works for me, thanks

**Comment by alexkravets** [comment]
+1
